// Firestore Schema for Pre-Generated Credentials Collection

export interface PreGeneratedCredentialSchema {
  // Basic Info
  id: string; // Document ID
  email: string;
  password: string; // Pre-generated password
  role: 'artist' | 'event_planner';
  displayName?: string;
  
  // Status
  used: boolean;
  usedAt?: Date;
  
  // Expiration
  expiresAt?: Date;
  
  // Metadata
  createdBy: string; // Admin UID who created this credential
  createdAt: Date;
  notes?: string; // Optional notes from admin
}

// Firestore Security Rules Example:
/*
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    // Only admins can read/write pre-generated credentials
    match /preGeneratedCredentials/{credentialId} {
      allow read, write: if request.auth != null && 
        exists(/databases/$(database)/documents/admins/$(request.auth.uid));
    }
  }
}
*/

// Example credential creation (admin function):
/*
const credential = {
  email: 'artist@example.com',
  password: 'Kj9#mN2$pL8', // Generated by admin
  role: 'artist',
  displayName: 'Jane Artist',
  used: false,
  expiresAt: new Date('2024-12-31'), // Optional expiration
  createdBy: 'admin-uid',
  createdAt: new Date(),
  notes: 'Invited for gallery opening'
};
*/ 